### ISSUE TITLE
About train_num_steps

### ISSUE THREAD

**Issue by iris0329** [GuHuangAI/DiffusionEdge#7]
Hi, Thanks a lot for the contribution of this code base; it makes it much easier to read and understand the pipeline of LDM.
In the VAE training stage, I found you set the `train_num_steps` to 150000. Could you give me some idea of how you decided on this number? If I use my own dataset, how can I adapt this number?

Thanks in advance.
Best wishes

**Comment by GuHuangAI** [comment]
@iris0329 
For every 10000 steps, we test the performance on training dataset and save the checkpoint. Therefore, we can evaluate approximately the model by the sampling results. I suggest that you set the train_num_steps to 150000 as default, since it is enough for general reconstruction tasks.
Besides, because the model uses the ema policy, the model of later iter usually performs better.
